const { Router } = require('express')
const UserController = require('./app/controllers/UserController')
const SessionController = require('./app/controllers/SessionController')
const FileController = require('./app/controllers/FileController')
const ProviderController = require('./app/controllers/ProviderController')
const AppointmentController = require('./app/controllers/AppointmentController')
const ScheduleController = require('./app/controllers/ScheduleController')
const NotificationController = require('./app/controllers/NotificationController')
const authMiddleware = require('./app/middlewares/auth')
const multer = require('multer')(require('./config/multer'))
const routes = new Router()

routes.post('/users', UserController.store)
routes.post('/sessions', SessionController.store)

routes.use(authMiddleware)
routes.post('/appointments', AppointmentController.store)
routes.get('/appointments', AppointmentController.index)
routes.delete('/appointments/:id', AppointmentController.delete)
routes.put('/users', UserController.update)
routes.post('/files', multer.single('file'),FileController.store)
routes.get('/notifications', NotificationController.index)
routes.get('/providers', ProviderController.index)
routes.get('/schedules', ScheduleController.index)
module.exports = routes